# Generated by Django 5.1.1 on 2024-10-08 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DC_Sups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sups/')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('power_type', models.CharField(choices=[('EL', 'EYELASER'), ('SS', 'SUPERSPEED'), ('RT', 'ROBOT'), ('SH', 'SUPERHUMAN_STRENGTH'), ('WM', 'WATER_MANIPULATION')], max_length=2)),
            ],
        ),
    ]
