# Generated by Django 5.1.1 on 2024-10-08 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_sups',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
