# Generated by Django 5.1.1 on 2024-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_alter_dc_sups_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_sups',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
